# https://pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.CosineAnnealingLR.html#torch.optim.lr_scheduler.CosineAnnealingLR
name: CosineAnnealingLR
parameter:
  T_max: 10 # Maximum number of iterations. guess that should be the number of epochs?
  eta_min: 0 # Minimum learning rate. Default: 0.
