defaults:
  - model: samba_S
  - trainer: base
  - dataset: nasa_S
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

keep_checkpoint: True
gpu_devices: auto
log_graph: False

hydra:
  sweeper:
    params:
      model/input_projection: linear_projection, local_time_embedding , local_time_global_diff_embedding
  sweep:
    dir: outputs/ablation/encodings/${now:%Y-%m-%d}/${now:%H-%M-%S}
