defaults:
  - model: samba_S
  - trainer: base
  - dataset: nasa_S
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

keep_checkpoint: True
gpu_devices: auto
log_graph: False

hydra:
  sweeper:
    params:
      model.cls_token_type: head,middle,tail,none
  sweep:
    dir: outputs/ablation/token/${now:%Y-%m-%d}/${now:%H-%M-%S}
