defaults:
  - model: samba_S
  - trainer: base
  - dataset: nasa_S
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

keep_checkpoint: True
gpu_devices: auto
log_graph: False

hydra:
  sweeper:
    params:
      model/backbone: vanilla_mamba , samba_mixer
  sweep:
    dir: outputs/ablation/backbone/${now:%Y-%m-%d}/${now:%H-%M-%S}
