defaults:
  - model: samba_S
  - trainer: base
  - dataset: oxford
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

keep_checkpoint: True
gpu_devices: auto
log_graph: False
